version: '3'
services:
  db:
    image: postgres:10.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./db/docker-entry-scripts:/docker-entrypoint-initdb.d/
