# serverless.yml

service: compete-backend

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  profile: default
  vpc:
    securityGroupIds:
      - sg-0c4c79ac5cf2c5023
    subnetdIds:
      - subnet-d758a0fa

functions:
  graphql:
    handler: src/index.handler
    events:
      - http:
          path: '{proxy+}'
          method: any
          cors:
            origin: '*' # <-- Specify allowed origin
            headers:    # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Apollo-Tracing
            allowCredentials: false
  decayRatings:
    handler: src/secondaryLambdas/decayRatings.handler
    events:
      - schedule:
          rate: cron(50 14 * * FRI *)
          enabled: true
  postRatings:
    handler: src/secondaryLambdas/postRatings.handler
    events:
      - schedule:
          rate: cron(0 15 * * FRI *)
          enabled: true

plugins:
  - serverless-offline
